apiVersion: v1
kind: Service
metadata:
  name: a2k-frontend
  namespace: a2k-frontend
  labels:
    app: a2k-frontend
spec:
  type: ClusterIP
  selector:
    app: a2k-frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
