apiVersion: v1
kind: Service
metadata:
  name: a2k-box
  namespace: a2k-box
  labels:
    app: a2k-box
spec:
  type: ClusterIP
  selector:
    app: a2k-box
  ports:
    - name: http
      port: 8080
      targetPort: http
